foods = [
  {
    id: 1,
    title: "burger 1",
    price: 10,
    imgPath: "./assets/images/burger 1.png",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 1,
    title: "burger 1",
    price: 10,
    imgPath: "./assets/images/burger 1.png",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 1,
    title: "burger 1",
    price: 10,
    imgPath: "./assets/images/burger 1.png",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 1,
    title: "burger 1",
    price: 10,
    imgPath: "./assets/images/burger 1.png",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 2,
    title: "burger 2",
    price: 10,
    imgPath: "./assets/images/burger 2.jpg",
    category: "1",
  },
  {
    id: 3,
    title: "pizza 1",
    price: 10,
    imgPath: "./assets/images/pizza 1.jpg",
    category: "2",
  },
  {
    id: 4,
    title: "pizza 2",
    price: 10,
    imgPath: "./assets/images/pizza 2.jpg",
    category: "2",
  },
  {
    id: 5,
    title: "sandwich 1",
    price: 10,
    imgPath: "./assets/images/sandwich 1.jpg",
    category: "3",
  },
  {
    id: 6,
    title: "sandwich 2",
    price: 10,
    imgPath: "./assets/images/sandwich 2.jpg",
    category: "3",
  },
  {
    id: 7,
    title: "eth 1",
    price: 10,
    imgPath: "./assets/images/eth 1.jpg",
    category: "4",
  },
  {
    id: 8,
    title: "seth 2",
    price: 10,
    imgPath: "./assets/images/eth 2.jpg",
    category: "4",
  },
];
